
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 22:32:48 IST (Feb 22 2025 17:02:48 UTC)

// Verification Directory fv/fa

module fa(sum, cout, a, b, cin);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFX2 g85__2398(.A (a), .B (cin), .CI (b), .CO (cout), .S (sum));
endmodule

