
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 22:23:20 IST (Feb 22 2025 16:53:20 UTC)

// Verification Directory fv/counter_32

module counter_32(clk, rst, m, count);
  input clk, rst, m;
  output [31:0] count;
  wire clk, rst, m;
  wire [31:0] count;
  wire \count[0]_231 , \count[1]_232 , \count[2]_233 , \count[3]_234 ,
       \count[4]_235 , \count[5]_236 , \count[6]_237 , \count[7]_238 ;
  wire \count[8]_239 , \count[9]_240 , \count[10]_241 , \count[11]_242
       , \count[12]_243 , \count[13]_244 , \count[14]_245 ,
       \count[15]_246 ;
  wire \count[16]_247 , \count[17]_248 , \count[18]_249 ,
       \count[19]_250 , \count[20]_251 , \count[21]_252 ,
       \count[24]_255 , \count[25]_256 ;
  wire dec_sub_13_18_n_2, dec_sub_13_18_n_3, dec_sub_13_18_n_4,
       dec_sub_13_18_n_6, dec_sub_13_18_n_7, dec_sub_13_18_n_8,
       dec_sub_13_18_n_9, dec_sub_13_18_n_10;
  wire dec_sub_13_18_n_11, dec_sub_13_18_n_12, dec_sub_13_18_n_13,
       dec_sub_13_18_n_14, dec_sub_13_18_n_15, dec_sub_13_18_n_17,
       dec_sub_13_18_n_18, dec_sub_13_18_n_20;
  wire dec_sub_13_18_n_21, dec_sub_13_18_n_24, dec_sub_13_18_n_25,
       dec_sub_13_18_n_27, dec_sub_13_18_n_28, dec_sub_13_18_n_30,
       dec_sub_13_18_n_31, dec_sub_13_18_n_34;
  wire dec_sub_13_18_n_35, dec_sub_13_18_n_36, dec_sub_13_18_n_37,
       dec_sub_13_18_n_38, dec_sub_13_18_n_39, dec_sub_13_18_n_40,
       dec_sub_13_18_n_41, dec_sub_13_18_n_42;
  wire dec_sub_13_18_n_44, dec_sub_13_18_n_45, dec_sub_13_18_n_49,
       dec_sub_13_18_n_50, dec_sub_13_18_n_51, dec_sub_13_18_n_52,
       dec_sub_13_18_n_54, dec_sub_13_18_n_57;
  wire dec_sub_13_18_n_58, dec_sub_13_18_n_59, dec_sub_13_18_n_60,
       dec_sub_13_18_n_61, dec_sub_13_18_n_62, dec_sub_13_18_n_63,
       dec_sub_13_18_n_72, inc_add_11_18_n_1;
  wire inc_add_11_18_n_2, inc_add_11_18_n_3, inc_add_11_18_n_4,
       inc_add_11_18_n_5, inc_add_11_18_n_6, inc_add_11_18_n_7,
       inc_add_11_18_n_8, inc_add_11_18_n_9;
  wire inc_add_11_18_n_10, inc_add_11_18_n_11, inc_add_11_18_n_13,
       inc_add_11_18_n_14, inc_add_11_18_n_15, inc_add_11_18_n_16,
       inc_add_11_18_n_17, inc_add_11_18_n_19;
  wire inc_add_11_18_n_20, inc_add_11_18_n_21, inc_add_11_18_n_23,
       inc_add_11_18_n_24, inc_add_11_18_n_27, inc_add_11_18_n_29,
       inc_add_11_18_n_30, inc_add_11_18_n_31;
  wire inc_add_11_18_n_33, inc_add_11_18_n_35, inc_add_11_18_n_36,
       inc_add_11_18_n_37, inc_add_11_18_n_40, inc_add_11_18_n_41,
       inc_add_11_18_n_42, inc_add_11_18_n_43;
  wire inc_add_11_18_n_44, inc_add_11_18_n_47, inc_add_11_18_n_49,
       inc_add_11_18_n_50, inc_add_11_18_n_51, inc_add_11_18_n_52,
       inc_add_11_18_n_55, inc_add_11_18_n_56;
  wire inc_add_11_18_n_57, inc_add_11_18_n_60, inc_add_11_18_n_62,
       inc_add_11_18_n_63, inc_add_11_18_n_64, inc_add_11_18_n_65,
       inc_add_11_18_n_68, inc_add_11_18_n_70;
  wire inc_add_11_18_n_71, inc_add_11_18_n_72, inc_add_11_18_n_75,
       inc_add_11_18_n_76, inc_add_11_18_n_77, inc_add_11_18_n_78,
       inc_add_11_18_n_82, inc_add_11_18_n_83;
  wire inc_add_11_18_n_86, inc_add_11_18_n_87, inc_add_11_18_n_90,
       inc_add_11_18_n_92, n_0, n_1, n_3, n_4;
  wire n_5, n_6, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_127, n_128, n_129, n_130, n_131, n_132;
  BUFX2 g279(.A (\count[8]_239 ), .Y (count[8]));
  BUFX2 g256(.A (\count[24]_255 ), .Y (count[24]));
  BUFX2 g252(.A (\count[10]_241 ), .Y (count[10]));
  BUFX2 g254(.A (\count[9]_240 ), .Y (count[9]));
  BUFX2 g260(.A (\count[16]_247 ), .Y (count[16]));
  BUFX2 g271(.A (\count[11]_242 ), .Y (count[11]));
  BUFX2 g265(.A (\count[19]_250 ), .Y (count[19]));
  BUFX2 g276(.A (\count[18]_249 ), .Y (count[18]));
  BUFX2 g273(.A (\count[17]_248 ), .Y (count[17]));
  BUFX2 g275(.A (\count[6]_237 ), .Y (count[6]));
  BUFX2 g270(.A (\count[20]_251 ), .Y (count[20]));
  BUFX2 g269(.A (\count[1]_232 ), .Y (count[1]));
  BUFX2 g267(.A (\count[7]_238 ), .Y (count[7]));
  BUFX2 g251(.A (\count[12]_243 ), .Y (count[12]));
  BUFX2 g259(.A (\count[15]_246 ), .Y (count[15]));
  BUFX2 g282(.A (\count[0]_231 ), .Y (count[0]));
  BUFX2 g284(.A (\count[5]_236 ), .Y (count[5]));
  BUFX2 g258(.A (\count[21]_252 ), .Y (count[21]));
  BUFX2 g264(.A (\count[2]_233 ), .Y (count[2]));
  BUFX2 g268(.A (\count[3]_234 ), .Y (count[3]));
  BUFX2 g283(.A (\count[4]_235 ), .Y (count[4]));
  BUFX2 g281(.A (\count[13]_244 ), .Y (count[13]));
  BUFX2 g278(.A (\count[14]_245 ), .Y (count[14]));
  BUFX2 g263(.A (\count[25]_256 ), .Y (count[25]));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_73), .SI (n_42),
       .SE (n_1), .Q (\count[1]_232 ));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_74), .SI (n_43),
       .SE (n_1), .Q (\count[2]_233 ));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_75), .SI (n_44),
       .SE (m), .Q (\count[3]_234 ));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_76), .SI (n_45),
       .SE (m), .Q (\count[4]_235 ));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_77), .SI (n_46),
       .SE (m), .Q (\count[5]_236 ));
  SDFFRHQX2 \count_reg[6] (.RN (rst), .CK (clk), .D (n_78), .SI (n_47),
       .SE (n_1), .Q (\count[6]_237 ));
  SDFFRHQX2 \count_reg[7] (.RN (rst), .CK (clk), .D (n_79), .SI (n_48),
       .SE (n_1), .Q (\count[7]_238 ));
  SDFFRHQX1 \count_reg[8] (.RN (rst), .CK (clk), .D (n_80), .SI (n_49),
       .SE (m), .Q (\count[8]_239 ));
  SDFFRHQX1 \count_reg[9] (.RN (rst), .CK (clk), .D (n_81), .SI (n_50),
       .SE (n_1), .Q (\count[9]_240 ));
  SDFFRHQX1 \count_reg[10] (.RN (rst), .CK (clk), .D (n_82), .SI
       (n_51), .SE (m), .Q (\count[10]_241 ));
  SDFFRHQX1 \count_reg[11] (.RN (rst), .CK (clk), .D (n_83), .SI
       (n_52), .SE (m), .Q (\count[11]_242 ));
  SDFFRHQX1 \count_reg[12] (.RN (rst), .CK (clk), .D (n_84), .SI
       (n_53), .SE (n_1), .Q (\count[12]_243 ));
  SDFFRHQX1 \count_reg[13] (.RN (rst), .CK (clk), .D (n_85), .SI
       (n_54), .SE (m), .Q (\count[13]_244 ));
  SDFFRHQX1 \count_reg[14] (.RN (rst), .CK (clk), .D (n_86), .SI
       (n_55), .SE (m), .Q (\count[14]_245 ));
  SDFFRHQX1 \count_reg[15] (.RN (rst), .CK (clk), .D (n_87), .SI
       (n_56), .SE (n_1), .Q (\count[15]_246 ));
  SDFFRHQX1 \count_reg[16] (.RN (rst), .CK (clk), .D (n_88), .SI
       (n_57), .SE (m), .Q (\count[16]_247 ));
  SDFFRHQX1 \count_reg[17] (.RN (rst), .CK (clk), .D (n_89), .SI
       (n_58), .SE (n_1), .Q (\count[17]_248 ));
  SDFFRHQX1 \count_reg[18] (.RN (rst), .CK (clk), .D (n_90), .SI
       (n_59), .SE (m), .Q (\count[18]_249 ));
  SDFFRHQX1 \count_reg[19] (.RN (rst), .CK (clk), .D (n_91), .SI
       (n_60), .SE (m), .Q (\count[19]_250 ));
  SDFFRHQX1 \count_reg[20] (.RN (rst), .CK (clk), .D (n_92), .SI
       (n_61), .SE (m), .Q (\count[20]_251 ));
  SDFFRHQX1 \count_reg[21] (.RN (rst), .CK (clk), .D (n_93), .SI
       (n_62), .SE (m), .Q (\count[21]_252 ));
  SDFFRHQX1 \count_reg[22] (.RN (rst), .CK (clk), .D (n_94), .SI
       (n_63), .SE (n_1), .Q (n_4));
  SDFFRHQX4 \count_reg[23] (.RN (rst), .CK (clk), .D (n_95), .SI
       (n_64), .SE (m), .Q (count[23]));
  SDFFRHQX1 \count_reg[24] (.RN (rst), .CK (clk), .D (n_96), .SI
       (n_65), .SE (n_1), .Q (\count[24]_255 ));
  SDFFRHQX1 \count_reg[25] (.RN (rst), .CK (clk), .D (n_97), .SI
       (n_66), .SE (n_1), .Q (\count[25]_256 ));
  SDFFRHQX1 \count_reg[26] (.RN (rst), .CK (clk), .D (n_98), .SI
       (n_67), .SE (n_1), .Q (n_5));
  SDFFRHQX4 \count_reg[27] (.RN (rst), .CK (clk), .D (n_99), .SI
       (n_68), .SE (n_1), .Q (count[27]));
  SDFFRHQX1 \count_reg[29] (.RN (rst), .CK (clk), .D (n_101), .SI
       (n_70), .SE (m), .Q (n_6));
  SDFFRHQX4 \count_reg[30] (.RN (rst), .CK (clk), .D (n_102), .SI
       (n_71), .SE (n_1), .Q (count[30]));
  SDFFRHQX2 \count_reg[31] (.RN (rst), .CK (clk), .D (n_103), .SI
       (n_72), .SE (n_1), .Q (count[31]));
  CLKINVX1 drc_bufs844(.A (n_0), .Y (n_1));
  CLKINVX1 drc_bufs845(.A (m), .Y (n_0));
  BUFX3 g846(.A (n_4), .Y (count[22]));
  BUFX2 g847(.A (n_5), .Y (count[26]));
  BUFX2 g848(.A (n_6), .Y (count[29]));
  OAI2BB1XL dec_sub_13_18_g410__2398(.A0N (\count[17]_248 ), .A1N
       (dec_sub_13_18_n_63), .B0 (dec_sub_13_18_n_61), .Y (n_89));
  OAI2BB1X1 dec_sub_13_18_g411__5107(.A0N (\count[9]_240 ), .A1N
       (dec_sub_13_18_n_44), .B0 (dec_sub_13_18_n_45), .Y (n_81));
  OAI2BB1XL dec_sub_13_18_g412__6260(.A0N (\count[21]_252 ), .A1N
       (n_129), .B0 (dec_sub_13_18_n_62), .Y (n_93));
  OAI2BB1XL dec_sub_13_18_g413__4319(.A0N (\count[20]_251 ), .A1N
       (dec_sub_13_18_n_59), .B0 (n_129), .Y (n_92));
  OAI2BB1XL dec_sub_13_18_g414__8428(.A0N (count[28]), .A1N
       (dec_sub_13_18_n_51), .B0 (n_128), .Y (n_100));
  OAI2BB1X1 dec_sub_13_18_g415__5526(.A0N (\count[5]_236 ), .A1N
       (dec_sub_13_18_n_35), .B0 (dec_sub_13_18_n_34), .Y (n_77));
  OAI2BB1XL dec_sub_13_18_g416__6783(.A0N (count[29]), .A1N (n_128),
       .B0 (dec_sub_13_18_n_52), .Y (n_101));
  OAI2BB1XL dec_sub_13_18_g417__3680(.A0N (\count[25]_256 ), .A1N
       (dec_sub_13_18_n_57), .B0 (dec_sub_13_18_n_58), .Y (n_97));
  OAI2BB1XL dec_sub_13_18_g418__1617(.A0N (\count[24]_255 ), .A1N
       (dec_sub_13_18_n_60), .B0 (dec_sub_13_18_n_57), .Y (n_96));
  OAI2BB1XL dec_sub_13_18_g419__2802(.A0N (count[26]), .A1N
       (dec_sub_13_18_n_58), .B0 (dec_sub_13_18_n_49), .Y (n_98));
  OAI2BB1XL dec_sub_13_18_g420__1705(.A0N (count[22]), .A1N
       (dec_sub_13_18_n_62), .B0 (dec_sub_13_18_n_54), .Y (n_94));
  OAI2BB1XL dec_sub_13_18_g421__5122(.A0N (\count[19]_250 ), .A1N
       (dec_sub_13_18_n_50), .B0 (dec_sub_13_18_n_59), .Y (n_91));
  OAI2BB1XL dec_sub_13_18_g422__8246(.A0N (\count[18]_249 ), .A1N
       (dec_sub_13_18_n_61), .B0 (dec_sub_13_18_n_50), .Y (n_90));
  OAI2BB1XL dec_sub_13_18_g423__7098(.A0N (count[30]), .A1N
       (dec_sub_13_18_n_52), .B0 (n_127), .Y (n_102));
  OAI2BB1XL dec_sub_13_18_g424__6131(.A0N (count[23]), .A1N
       (dec_sub_13_18_n_54), .B0 (dec_sub_13_18_n_60), .Y (n_95));
  OAI2BB1XL dec_sub_13_18_g425__1881(.A0N (count[27]), .A1N
       (dec_sub_13_18_n_49), .B0 (dec_sub_13_18_n_51), .Y (n_99));
  OAI21X1 dec_sub_13_18_g426__5115(.A0 (count[31]), .A1 (n_127), .B0
       (dec_sub_13_18_n_72), .Y (n_103));
  NAND2XL dec_sub_13_18_g427__7482(.A (count[31]), .B (n_127), .Y
       (dec_sub_13_18_n_72));
  OAI2BB1X1 dec_sub_13_18_g428__4733(.A0N (\count[12]_243 ), .A1N
       (dec_sub_13_18_n_42), .B0 (dec_sub_13_18_n_38), .Y (n_84));
  OAI2BB1XL dec_sub_13_18_g429__6161(.A0N (\count[16]_247 ), .A1N
       (dec_sub_13_18_n_40), .B0 (dec_sub_13_18_n_63), .Y (n_88));
  OAI2BB1X1 dec_sub_13_18_g430__9315(.A0N (\count[13]_244 ), .A1N
       (dec_sub_13_18_n_38), .B0 (dec_sub_13_18_n_39), .Y (n_85));
  OAI2BB1X1 dec_sub_13_18_g431__9945(.A0N (\count[14]_245 ), .A1N
       (dec_sub_13_18_n_39), .B0 (dec_sub_13_18_n_36), .Y (n_86));
  OAI2BB1X1 dec_sub_13_18_g432__2883(.A0N (\count[11]_242 ), .A1N
       (dec_sub_13_18_n_37), .B0 (dec_sub_13_18_n_42), .Y (n_83));
  OAI2BB1X1 dec_sub_13_18_g433__2346(.A0N (\count[10]_241 ), .A1N
       (dec_sub_13_18_n_45), .B0 (dec_sub_13_18_n_37), .Y (n_82));
  OAI2BB1X1 dec_sub_13_18_g434__1666(.A0N (\count[3]_234 ), .A1N
       (dec_sub_13_18_n_30), .B0 (dec_sub_13_18_n_2), .Y (n_75));
  OAI2BB1X1 dec_sub_13_18_g435__7410(.A0N (\count[15]_246 ), .A1N
       (dec_sub_13_18_n_36), .B0 (dec_sub_13_18_n_40), .Y (n_87));
  OAI2BB1X1 dec_sub_13_18_g436__6417(.A0N (\count[8]_239 ), .A1N
       (dec_sub_13_18_n_3), .B0 (dec_sub_13_18_n_44), .Y (n_80));
  NAND2BX1 dec_sub_13_18_g437__5477(.AN (\count[16]_247 ), .B
       (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_63));
  NAND3X1 dec_sub_13_18_g438__2398(.A (dec_sub_13_18_n_7), .B (n_131),
       .C (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_62));
  NAND2XL dec_sub_13_18_g439__5107(.A (dec_sub_13_18_n_10), .B
       (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_61));
  NAND2XL dec_sub_13_18_g440__6260(.A (dec_sub_13_18_n_25), .B
       (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_60));
  NAND2XL dec_sub_13_18_g441__4319(.A (n_131), .B (dec_sub_13_18_n_41),
       .Y (dec_sub_13_18_n_59));
  NAND3X1 dec_sub_13_18_g442__8428(.A (dec_sub_13_18_n_8), .B
       (dec_sub_13_18_n_25), .C (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_58));
  NAND3BX1 dec_sub_13_18_g443__5526(.AN (\count[24]_255 ), .B
       (dec_sub_13_18_n_25), .C (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_57));
  OAI2BB1X1 dec_sub_13_18_g445__3680(.A0N (\count[7]_238 ), .A1N
       (dec_sub_13_18_n_31), .B0 (dec_sub_13_18_n_3), .Y (n_79));
  OAI2BB1X1 dec_sub_13_18_g446__1617(.A0N (\count[6]_237 ), .A1N
       (dec_sub_13_18_n_34), .B0 (dec_sub_13_18_n_31), .Y (n_78));
  NAND4BXL dec_sub_13_18_g447__2802(.AN (count[22]), .B
       (dec_sub_13_18_n_7), .C (n_131), .D (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_54));
  NAND4XL dec_sub_13_18_g449__5122(.A (dec_sub_13_18_n_11), .B
       (dec_sub_13_18_n_21), .C (dec_sub_13_18_n_25), .D
       (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_52));
  NAND3X1 dec_sub_13_18_g450__8246(.A (dec_sub_13_18_n_21), .B
       (dec_sub_13_18_n_25), .C (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_51));
  NAND3BX1 dec_sub_13_18_g451__7098(.AN (\count[18]_249 ), .B
       (dec_sub_13_18_n_10), .C (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_50));
  NAND4BXL dec_sub_13_18_g452__6131(.AN (count[26]), .B
       (dec_sub_13_18_n_8), .C (dec_sub_13_18_n_25), .D
       (dec_sub_13_18_n_41), .Y (dec_sub_13_18_n_49));
  NAND2XL dec_sub_13_18_g454__5115(.A (dec_sub_13_18_n_17), .B
       (dec_sub_13_18_n_4), .Y (dec_sub_13_18_n_45));
  NAND2BX1 dec_sub_13_18_g455__7482(.AN (\count[8]_239 ), .B
       (dec_sub_13_18_n_4), .Y (dec_sub_13_18_n_44));
  OAI2BB1X1 dec_sub_13_18_g456__4733(.A0N (\count[4]_235 ), .A1N
       (dec_sub_13_18_n_2), .B0 (dec_sub_13_18_n_35), .Y (n_76));
  NAND2XL dec_sub_13_18_g457__6161(.A (n_130), .B (dec_sub_13_18_n_4),
       .Y (dec_sub_13_18_n_42));
  CLKINVX1 dec_sub_13_18_g458(.A (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_40));
  AND4X2 dec_sub_13_18_g459__9315(.A (dec_sub_13_18_n_14), .B
       (dec_sub_13_18_n_9), .C (n_130), .D (dec_sub_13_18_n_4), .Y
       (dec_sub_13_18_n_41));
  NAND3X1 dec_sub_13_18_g460__9945(.A (dec_sub_13_18_n_9), .B (n_130),
       .C (dec_sub_13_18_n_4), .Y (dec_sub_13_18_n_39));
  NAND3BX1 dec_sub_13_18_g461__2883(.AN (\count[12]_243 ), .B (n_130),
       .C (dec_sub_13_18_n_4), .Y (dec_sub_13_18_n_38));
  NAND3BX1 dec_sub_13_18_g462__2346(.AN (\count[10]_241 ), .B
       (dec_sub_13_18_n_17), .C (dec_sub_13_18_n_4), .Y
       (dec_sub_13_18_n_37));
  NAND4BXL dec_sub_13_18_g463__1666(.AN (\count[14]_245 ), .B
       (dec_sub_13_18_n_9), .C (n_130), .D (dec_sub_13_18_n_4), .Y
       (dec_sub_13_18_n_36));
  OR2X1 dec_sub_13_18_g464__7410(.A (\count[4]_235 ), .B
       (dec_sub_13_18_n_2), .Y (dec_sub_13_18_n_35));
  NAND2XL dec_sub_13_18_g465__6417(.A (dec_sub_13_18_n_18), .B
       (dec_sub_13_18_n_28), .Y (dec_sub_13_18_n_34));
  OAI2BB1X1 dec_sub_13_18_g466__5477(.A0N (\count[2]_233 ), .A1N
       (dec_sub_13_18_n_27), .B0 (dec_sub_13_18_n_30), .Y (n_74));
  CLKINVX1 dec_sub_13_18_g470(.A (dec_sub_13_18_n_4), .Y
       (dec_sub_13_18_n_3));
  NOR2X2 dec_sub_13_18_g472__2398(.A (dec_sub_13_18_n_20), .B
       (dec_sub_13_18_n_2), .Y (dec_sub_13_18_n_4));
  NAND3BX1 dec_sub_13_18_g473__5107(.AN (\count[6]_237 ), .B
       (dec_sub_13_18_n_18), .C (dec_sub_13_18_n_28), .Y
       (dec_sub_13_18_n_31));
  OR2X1 dec_sub_13_18_g474__6260(.A (\count[2]_233 ), .B
       (dec_sub_13_18_n_27), .Y (dec_sub_13_18_n_30));
  CLKINVX1 dec_sub_13_18_g477(.A (dec_sub_13_18_n_2), .Y
       (dec_sub_13_18_n_28));
  NAND2X1 dec_sub_13_18_g478__4319(.A (dec_sub_13_18_n_12), .B
       (dec_sub_13_18_n_6), .Y (dec_sub_13_18_n_2));
  CLKINVX1 dec_sub_13_18_g480(.A (dec_sub_13_18_n_6), .Y
       (dec_sub_13_18_n_27));
  AND3X1 dec_sub_13_18_g484__5526(.A (dec_sub_13_18_n_13), .B
       (dec_sub_13_18_n_7), .C (n_131), .Y (dec_sub_13_18_n_25));
  NAND3BX1 dec_sub_13_18_g485__6783(.AN (count[30]), .B
       (dec_sub_13_18_n_11), .C (dec_sub_13_18_n_21), .Y
       (dec_sub_13_18_n_24));
  AO21X1 dec_sub_13_18_g486__3680(.A0 (\count[0]_231 ), .A1
       (\count[1]_232 ), .B0 (dec_sub_13_18_n_6), .Y (n_73));
  NOR3BX1 dec_sub_13_18_g488__2802(.AN (dec_sub_13_18_n_8), .B
       (count[27]), .C (count[26]), .Y (dec_sub_13_18_n_21));
  NAND2XL dec_sub_13_18_g489__1705(.A (dec_sub_13_18_n_15), .B
       (dec_sub_13_18_n_18), .Y (dec_sub_13_18_n_20));
  NOR2XL dec_sub_13_18_g493__7098(.A (\count[7]_238 ), .B
       (\count[6]_237 ), .Y (dec_sub_13_18_n_15));
  NOR2XL dec_sub_13_18_g494__6131(.A (\count[15]_246 ), .B
       (\count[14]_245 ), .Y (dec_sub_13_18_n_14));
  NOR2XL dec_sub_13_18_g495__1881(.A (count[23]), .B (count[22]), .Y
       (dec_sub_13_18_n_13));
  NOR2XL dec_sub_13_18_g496__5115(.A (\count[3]_234 ), .B
       (\count[2]_233 ), .Y (dec_sub_13_18_n_12));
  NOR2XL dec_sub_13_18_g497__7482(.A (\count[5]_236 ), .B
       (\count[4]_235 ), .Y (dec_sub_13_18_n_18));
  NOR2XL dec_sub_13_18_g498__4733(.A (\count[9]_240 ), .B
       (\count[8]_239 ), .Y (dec_sub_13_18_n_17));
  NOR2XL dec_sub_13_18_g500__9315(.A (count[29]), .B (count[28]), .Y
       (dec_sub_13_18_n_11));
  NOR2XL dec_sub_13_18_g501__9945(.A (\count[17]_248 ), .B
       (\count[16]_247 ), .Y (dec_sub_13_18_n_10));
  NOR2XL dec_sub_13_18_g502__2883(.A (\count[13]_244 ), .B
       (\count[12]_243 ), .Y (dec_sub_13_18_n_9));
  NOR2XL dec_sub_13_18_g503__2346(.A (\count[25]_256 ), .B
       (\count[24]_255 ), .Y (dec_sub_13_18_n_8));
  NOR2XL dec_sub_13_18_g504__1666(.A (\count[21]_252 ), .B
       (\count[20]_251 ), .Y (dec_sub_13_18_n_7));
  NOR2X1 dec_sub_13_18_g505__7410(.A (\count[1]_232 ), .B
       (\count[0]_231 ), .Y (dec_sub_13_18_n_6));
  OAI21X1 inc_add_11_18_g479__2398(.A0 (\count[19]_250 ), .A1
       (inc_add_11_18_n_82), .B0 (inc_add_11_18_n_92), .Y (n_60));
  NAND2XL inc_add_11_18_g480__5107(.A (\count[19]_250 ), .B
       (inc_add_11_18_n_82), .Y (inc_add_11_18_n_92));
  OAI21X1 inc_add_11_18_g481__6260(.A0 (count[31]), .A1
       (inc_add_11_18_n_77), .B0 (inc_add_11_18_n_90), .Y (n_72));
  NAND2XL inc_add_11_18_g482__4319(.A (count[31]), .B
       (inc_add_11_18_n_77), .Y (inc_add_11_18_n_90));
  OAI21X1 inc_add_11_18_g483__8428(.A0 (count[29]), .A1
       (inc_add_11_18_n_72), .B0 (inc_add_11_18_n_87), .Y (n_70));
  OAI21X1 inc_add_11_18_g484__5526(.A0 (\count[11]_242 ), .A1
       (inc_add_11_18_n_70), .B0 (inc_add_11_18_n_86), .Y (n_52));
  NAND2XL inc_add_11_18_g485__6783(.A (count[29]), .B
       (inc_add_11_18_n_72), .Y (inc_add_11_18_n_87));
  NAND2XL inc_add_11_18_g486__3680(.A (\count[11]_242 ), .B
       (inc_add_11_18_n_70), .Y (inc_add_11_18_n_86));
  OA21XL inc_add_11_18_g487__1617(.A0 (\count[18]_249 ), .A1
       (inc_add_11_18_n_62), .B0 (inc_add_11_18_n_82), .Y (n_59));
  OAI21X1 inc_add_11_18_g488__2802(.A0 (count[27]), .A1
       (inc_add_11_18_n_65), .B0 (inc_add_11_18_n_83), .Y (n_68));
  NAND2XL inc_add_11_18_g489__1705(.A (count[27]), .B
       (inc_add_11_18_n_65), .Y (inc_add_11_18_n_83));
  NAND2XL inc_add_11_18_g490__5122(.A (\count[18]_249 ), .B
       (inc_add_11_18_n_62), .Y (inc_add_11_18_n_82));
  AOI21X1 inc_add_11_18_g491__8246(.A0 (inc_add_11_18_n_3), .A1
       (inc_add_11_18_n_68), .B0 (inc_add_11_18_n_78), .Y (n_71));
  OAI21X1 inc_add_11_18_g492__7098(.A0 (count[25]), .A1
       (inc_add_11_18_n_57), .B0 (inc_add_11_18_n_76), .Y (n_66));
  OAI21X1 inc_add_11_18_g493__6131(.A0 (count[23]), .A1
       (inc_add_11_18_n_56), .B0 (inc_add_11_18_n_75), .Y (n_64));
  INVXL inc_add_11_18_g494(.A (inc_add_11_18_n_77), .Y
       (inc_add_11_18_n_78));
  NAND3BX2 inc_add_11_18_g495__1881(.AN (inc_add_11_18_n_7), .B
       (count[30]), .C (inc_add_11_18_n_60), .Y (inc_add_11_18_n_77));
  NAND2XL inc_add_11_18_g496__5115(.A (count[25]), .B
       (inc_add_11_18_n_57), .Y (inc_add_11_18_n_76));
  NAND2XL inc_add_11_18_g497__7482(.A (count[23]), .B
       (inc_add_11_18_n_56), .Y (inc_add_11_18_n_75));
  OA21XL inc_add_11_18_g498__4733(.A0 (\count[10]_241 ), .A1
       (inc_add_11_18_n_51), .B0 (inc_add_11_18_n_70), .Y (n_51));
  OAI21X1 inc_add_11_18_g500__6161(.A0 (\count[21]_252 ), .A1
       (inc_add_11_18_n_49), .B0 (inc_add_11_18_n_71), .Y (n_62));
  NAND2X1 inc_add_11_18_g502__9315(.A (count[28]), .B
       (inc_add_11_18_n_60), .Y (inc_add_11_18_n_72));
  NAND2XL inc_add_11_18_g503__9945(.A (\count[21]_252 ), .B
       (inc_add_11_18_n_49), .Y (inc_add_11_18_n_71));
  NAND2XL inc_add_11_18_g504__2883(.A (\count[10]_241 ), .B
       (inc_add_11_18_n_51), .Y (inc_add_11_18_n_70));
  OA21XL inc_add_11_18_g505__2346(.A0 (count[26]), .A1
       (inc_add_11_18_n_52), .B0 (inc_add_11_18_n_65), .Y (n_67));
  NAND2BX1 inc_add_11_18_g506__1666(.AN (inc_add_11_18_n_7), .B
       (inc_add_11_18_n_60), .Y (inc_add_11_18_n_68));
  OAI21X1 inc_add_11_18_g507__7410(.A0 (\count[17]_248 ), .A1
       (inc_add_11_18_n_42), .B0 (inc_add_11_18_n_64), .Y (n_58));
  OAI21X1 inc_add_11_18_g508__6417(.A0 (\count[15]_246 ), .A1
       (inc_add_11_18_n_40), .B0 (inc_add_11_18_n_63), .Y (n_56));
  NAND2XL inc_add_11_18_g509__5477(.A (count[26]), .B
       (inc_add_11_18_n_52), .Y (inc_add_11_18_n_65));
  NAND2XL inc_add_11_18_g510__2398(.A (\count[17]_248 ), .B
       (inc_add_11_18_n_42), .Y (inc_add_11_18_n_64));
  NAND2XL inc_add_11_18_g511__5107(.A (\count[15]_246 ), .B
       (inc_add_11_18_n_40), .Y (inc_add_11_18_n_63));
  NOR2BX1 inc_add_11_18_g512__6260(.AN (\count[17]_248 ), .B
       (inc_add_11_18_n_42), .Y (inc_add_11_18_n_62));
  OA21XL inc_add_11_18_g513__4319(.A0 (count[22]), .A1
       (inc_add_11_18_n_50), .B0 (inc_add_11_18_n_56), .Y (n_63));
  CLKAND2X2 inc_add_11_18_g514__8428(.A (inc_add_11_18_n_11), .B
       (inc_add_11_18_n_52), .Y (inc_add_11_18_n_60));
  OA21XL inc_add_11_18_g515__5526(.A0 (\count[24]_255 ), .A1
       (inc_add_11_18_n_47), .B0 (inc_add_11_18_n_57), .Y (n_65));
  OAI21X1 inc_add_11_18_g516__6783(.A0 (\count[13]_244 ), .A1
       (inc_add_11_18_n_35), .B0 (inc_add_11_18_n_55), .Y (n_54));
  NAND2XL inc_add_11_18_g517__3680(.A (\count[24]_255 ), .B
       (inc_add_11_18_n_47), .Y (inc_add_11_18_n_57));
  NAND2XL inc_add_11_18_g518__1617(.A (count[22]), .B
       (inc_add_11_18_n_50), .Y (inc_add_11_18_n_56));
  NAND2XL inc_add_11_18_g519__2802(.A (\count[13]_244 ), .B
       (inc_add_11_18_n_35), .Y (inc_add_11_18_n_55));
  AOI2BB1X1 inc_add_11_18_g520__1705(.A0N (\count[9]_240 ), .A1N
       (inc_add_11_18_n_31), .B0 (inc_add_11_18_n_51), .Y (n_50));
  OA21XL inc_add_11_18_g521__5122(.A0 (\count[20]_251 ), .A1
       (inc_add_11_18_n_43), .B0 (inc_add_11_18_n_49), .Y (n_61));
  NOR4X2 inc_add_11_18_g522__8246(.A (inc_add_11_18_n_6), .B
       (inc_add_11_18_n_14), .C (inc_add_11_18_n_16), .D
       (inc_add_11_18_n_33), .Y (inc_add_11_18_n_52));
  AND2X1 inc_add_11_18_g523__7098(.A (\count[9]_240 ), .B
       (inc_add_11_18_n_31), .Y (inc_add_11_18_n_51));
  NOR2BX1 inc_add_11_18_g524__6131(.AN (inc_add_11_18_n_43), .B
       (inc_add_11_18_n_10), .Y (inc_add_11_18_n_50));
  NAND2XL inc_add_11_18_g525__1881(.A (\count[20]_251 ), .B
       (inc_add_11_18_n_43), .Y (inc_add_11_18_n_49));
  OA21X1 inc_add_11_18_g526__5115(.A0 (\count[14]_245 ), .A1
       (inc_add_11_18_n_36), .B0 (inc_add_11_18_n_40), .Y (n_55));
  NOR2BX1 inc_add_11_18_g527__7482(.AN (inc_add_11_18_n_43), .B
       (inc_add_11_18_n_16), .Y (inc_add_11_18_n_47));
  AOI21X1 inc_add_11_18_g528__4733(.A0 (inc_add_11_18_n_4), .A1
       (inc_add_11_18_n_33), .B0 (inc_add_11_18_n_41), .Y (n_57));
  OAI21X1 inc_add_11_18_g529__6161(.A0 (\count[7]_238 ), .A1
       (inc_add_11_18_n_27), .B0 (inc_add_11_18_n_44), .Y (n_48));
  NAND2XL inc_add_11_18_g530__9315(.A (\count[7]_238 ), .B
       (inc_add_11_18_n_27), .Y (inc_add_11_18_n_44));
  NOR2X1 inc_add_11_18_g531__9945(.A (inc_add_11_18_n_14), .B
       (inc_add_11_18_n_33), .Y (inc_add_11_18_n_43));
  CLKINVX1 inc_add_11_18_g532(.A (inc_add_11_18_n_41), .Y
       (inc_add_11_18_n_42));
  NOR2X1 inc_add_11_18_g533__2883(.A (inc_add_11_18_n_4), .B
       (inc_add_11_18_n_33), .Y (inc_add_11_18_n_41));
  NAND2XL inc_add_11_18_g534__2346(.A (\count[14]_245 ), .B
       (inc_add_11_18_n_36), .Y (inc_add_11_18_n_40));
  OA21XL inc_add_11_18_g535__1666(.A0 (\count[12]_243 ), .A1
       (inc_add_11_18_n_29), .B0 (inc_add_11_18_n_35), .Y (n_53));
  OAI21X1 inc_add_11_18_g536__7410(.A0 (\count[5]_236 ), .A1
       (inc_add_11_18_n_24), .B0 (inc_add_11_18_n_37), .Y (n_46));
  NAND2XL inc_add_11_18_g537__6417(.A (\count[5]_236 ), .B
       (inc_add_11_18_n_24), .Y (inc_add_11_18_n_37));
  NOR2BX1 inc_add_11_18_g538__5477(.AN (inc_add_11_18_n_29), .B
       (inc_add_11_18_n_5), .Y (inc_add_11_18_n_36));
  NAND2XL inc_add_11_18_g539__2398(.A (\count[12]_243 ), .B
       (inc_add_11_18_n_29), .Y (inc_add_11_18_n_35));
  AOI21X1 inc_add_11_18_g540__5107(.A0 (inc_add_11_18_n_2), .A1
       (n_132), .B0 (inc_add_11_18_n_31), .Y (n_49));
  NAND2X2 inc_add_11_18_g541__6260(.A (inc_add_11_18_n_17), .B
       (inc_add_11_18_n_29), .Y (inc_add_11_18_n_33));
  OAI21X1 inc_add_11_18_g542__4319(.A0 (\count[3]_234 ), .A1
       (inc_add_11_18_n_21), .B0 (inc_add_11_18_n_30), .Y (n_44));
  NOR2XL inc_add_11_18_g543__8428(.A (inc_add_11_18_n_2), .B (n_132),
       .Y (inc_add_11_18_n_31));
  NAND2XL inc_add_11_18_g544__5526(.A (\count[3]_234 ), .B
       (inc_add_11_18_n_21), .Y (inc_add_11_18_n_30));
  NOR2X2 inc_add_11_18_g545__6783(.A (inc_add_11_18_n_15), .B (n_132),
       .Y (inc_add_11_18_n_29));
  OA21X1 inc_add_11_18_g546__3680(.A0 (\count[6]_237 ), .A1
       (inc_add_11_18_n_23), .B0 (inc_add_11_18_n_27), .Y (n_47));
  NAND2XL inc_add_11_18_g547__1617(.A (\count[6]_237 ), .B
       (inc_add_11_18_n_23), .Y (inc_add_11_18_n_27));
  OA21X1 inc_add_11_18_g548__2802(.A0 (\count[4]_235 ), .A1
       (inc_add_11_18_n_20), .B0 (inc_add_11_18_n_24), .Y (n_45));
  NAND2XL inc_add_11_18_g550__5122(.A (\count[4]_235 ), .B
       (inc_add_11_18_n_20), .Y (inc_add_11_18_n_24));
  CLKAND2X2 inc_add_11_18_g551__8246(.A (inc_add_11_18_n_8), .B
       (inc_add_11_18_n_20), .Y (inc_add_11_18_n_23));
  OA21X1 inc_add_11_18_g552__7098(.A0 (\count[2]_233 ), .A1
       (inc_add_11_18_n_19), .B0 (inc_add_11_18_n_21), .Y (n_43));
  NAND2XL inc_add_11_18_g553__6131(.A (\count[2]_233 ), .B
       (inc_add_11_18_n_19), .Y (inc_add_11_18_n_21));
  NOR2X1 inc_add_11_18_g554__1881(.A (inc_add_11_18_n_13), .B
       (inc_add_11_18_n_1), .Y (inc_add_11_18_n_20));
  CLKINVX1 inc_add_11_18_g555(.A (inc_add_11_18_n_1), .Y
       (inc_add_11_18_n_19));
  OA21X1 inc_add_11_18_g556__5115(.A0 (\count[1]_232 ), .A1
       (\count[0]_231 ), .B0 (inc_add_11_18_n_1), .Y (n_42));
  NOR2XL inc_add_11_18_g557__7482(.A (inc_add_11_18_n_9), .B
       (inc_add_11_18_n_5), .Y (inc_add_11_18_n_17));
  NAND3BX1 inc_add_11_18_g558__4733(.AN (inc_add_11_18_n_10), .B
       (count[23]), .C (count[22]), .Y (inc_add_11_18_n_16));
  NAND4XL inc_add_11_18_g559__6161(.A (\count[9]_240 ), .B
       (\count[8]_239 ), .C (\count[11]_242 ), .D (\count[10]_241 ), .Y
       (inc_add_11_18_n_15));
  NAND4XL inc_add_11_18_g560__9315(.A (\count[17]_248 ), .B
       (\count[16]_247 ), .C (\count[19]_250 ), .D (\count[18]_249 ),
       .Y (inc_add_11_18_n_14));
  NAND2XL inc_add_11_18_g561__9945(.A (\count[3]_234 ), .B
       (\count[2]_233 ), .Y (inc_add_11_18_n_13));
  NAND2X1 inc_add_11_18_g564__2346(.A (\count[1]_232 ), .B
       (\count[0]_231 ), .Y (inc_add_11_18_n_1));
  AND2X1 inc_add_11_18_g565__1666(.A (count[26]), .B (count[27]), .Y
       (inc_add_11_18_n_11));
  NAND2XL inc_add_11_18_g566__7410(.A (\count[21]_252 ), .B
       (\count[20]_251 ), .Y (inc_add_11_18_n_10));
  NAND2XL inc_add_11_18_g567__6417(.A (\count[15]_246 ), .B
       (\count[14]_245 ), .Y (inc_add_11_18_n_9));
  AND2XL inc_add_11_18_g568__5477(.A (\count[4]_235 ), .B
       (\count[5]_236 ), .Y (inc_add_11_18_n_8));
  NAND2XL inc_add_11_18_g569__2398(.A (count[29]), .B (count[28]), .Y
       (inc_add_11_18_n_7));
  NAND2XL inc_add_11_18_g570__5107(.A (count[25]), .B (\count[24]_255
       ), .Y (inc_add_11_18_n_6));
  NAND2XL inc_add_11_18_g571__6260(.A (\count[13]_244 ), .B
       (\count[12]_243 ), .Y (inc_add_11_18_n_5));
  INVX1 inc_add_11_18_g572(.A (\count[16]_247 ), .Y
       (inc_add_11_18_n_4));
  INVXL inc_add_11_18_g573(.A (count[30]), .Y (inc_add_11_18_n_3));
  CLKINVX1 inc_add_11_18_g574(.A (\count[8]_239 ), .Y
       (inc_add_11_18_n_2));
  OA21XL inc_add_11_18_g2__4319(.A0 (count[28]), .A1
       (inc_add_11_18_n_60), .B0 (inc_add_11_18_n_72), .Y (n_69));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_3), .Q
       (\count[0]_231 ), .QN (n_3));
  NAND3BX1 g2(.AN (dec_sub_13_18_n_24), .B (dec_sub_13_18_n_41), .C
       (dec_sub_13_18_n_25), .Y (n_127));
  NAND4BXL g851(.AN (count[28]), .B (dec_sub_13_18_n_21), .C
       (dec_sub_13_18_n_25), .D (dec_sub_13_18_n_41), .Y (n_128));
  NAND3BX1 g852(.AN (\count[20]_251 ), .B (n_131), .C
       (dec_sub_13_18_n_41), .Y (n_129));
  NOR3BX1 g853(.AN (dec_sub_13_18_n_17), .B (\count[11]_242 ), .C
       (\count[10]_241 ), .Y (n_130));
  NOR3BX1 g854(.AN (dec_sub_13_18_n_10), .B (\count[19]_250 ), .C
       (\count[18]_249 ), .Y (n_131));
  NAND3X2 g855(.A (\count[7]_238 ), .B (\count[6]_237 ), .C
       (inc_add_11_18_n_23), .Y (n_132));
  SDFFRHQX2 \count_reg[28] (.RN (rst), .CK (clk), .D (n_100), .SI
       (n_69), .SE (n_1), .Q (count[28]));
endmodule

