
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 22:41:09 IST (Feb 22 2025 17:11:09 UTC)

// Verification Directory fv/counter

module counter(clk, rst, m, count);
  input clk, rst, m;
  output [3:0] count;
  wire clk, rst, m;
  wire [3:0] count;
  wire n_0, n_1, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14;
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_14), .SI (n_13),
       .SE (m), .Q (count[3]));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_10), .SI (n_9),
       .SE (m), .Q (count[2]));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (m), .SI (n_0), .SE
       (n_4), .Q (count[1]));
  OAI21X1 g246__2398(.A0 (count[3]), .A1 (n_11), .B0 (n_12), .Y (n_14));
  XOR2XL g247__5107(.A (n_6), .B (count[3]), .Y (n_13));
  NAND2XL g249__6260(.A (n_11), .B (count[3]), .Y (n_12));
  OAI21X1 g250__4319(.A0 (n_8), .A1 (n_7), .B0 (n_11), .Y (n_10));
  MXI2XL g251__8428(.A (count[2]), .B (n_8), .S0 (n_5), .Y (n_9));
  NAND2XL g252__5526(.A (n_7), .B (n_8), .Y (n_11));
  NOR2XL g253__6783(.A (n_8), .B (n_5), .Y (n_6));
  NAND2BXL g254__3680(.AN (n_7), .B (n_5), .Y (n_4));
  NOR2XL g256__1617(.A (count[1]), .B (count[0]), .Y (n_7));
  NAND2XL g257__2802(.A (count[0]), .B (count[1]), .Y (n_5));
  CLKINVX1 g264(.A (m), .Y (n_0));
  CLKINVX1 g259(.A (count[2]), .Y (n_8));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
endmodule

