
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 22:46:00 IST (Feb 22 2025 17:16:00 UTC)

// Verification Directory fv/counter_32

module counter_32(clk, rst, m, count);
  input clk, rst, m;
  output [31:0] count;
  wire clk, rst, m;
  wire [31:0] count;
  wire dec_sub_13_18_n_0, dec_sub_13_18_n_1, dec_sub_13_18_n_2,
       dec_sub_13_18_n_3, dec_sub_13_18_n_4, dec_sub_13_18_n_5,
       dec_sub_13_18_n_6, dec_sub_13_18_n_7;
  wire dec_sub_13_18_n_8, dec_sub_13_18_n_9, dec_sub_13_18_n_10,
       dec_sub_13_18_n_12, dec_sub_13_18_n_13, dec_sub_13_18_n_14,
       dec_sub_13_18_n_16, dec_sub_13_18_n_17;
  wire dec_sub_13_18_n_19, dec_sub_13_18_n_20, dec_sub_13_18_n_21,
       dec_sub_13_18_n_23, dec_sub_13_18_n_25, dec_sub_13_18_n_26,
       dec_sub_13_18_n_28, dec_sub_13_18_n_29;
  wire dec_sub_13_18_n_32, dec_sub_13_18_n_33, dec_sub_13_18_n_34,
       dec_sub_13_18_n_35, dec_sub_13_18_n_36, dec_sub_13_18_n_37,
       dec_sub_13_18_n_38, dec_sub_13_18_n_41;
  wire dec_sub_13_18_n_42, dec_sub_13_18_n_43, dec_sub_13_18_n_44,
       dec_sub_13_18_n_45, dec_sub_13_18_n_46, dec_sub_13_18_n_47,
       dec_sub_13_18_n_48, dec_sub_13_18_n_49;
  wire dec_sub_13_18_n_56, dec_sub_13_18_n_57, dec_sub_13_18_n_63,
       dec_sub_13_18_n_71, inc_add_11_18_n_0, inc_add_11_18_n_1,
       inc_add_11_18_n_2, inc_add_11_18_n_3;
  wire inc_add_11_18_n_4, inc_add_11_18_n_5, inc_add_11_18_n_6,
       inc_add_11_18_n_8, inc_add_11_18_n_9, inc_add_11_18_n_10,
       inc_add_11_18_n_11, inc_add_11_18_n_12;
  wire inc_add_11_18_n_13, inc_add_11_18_n_14, inc_add_11_18_n_16,
       inc_add_11_18_n_17, inc_add_11_18_n_18, inc_add_11_18_n_20,
       inc_add_11_18_n_21, inc_add_11_18_n_22;
  wire inc_add_11_18_n_23, inc_add_11_18_n_26, inc_add_11_18_n_27,
       inc_add_11_18_n_28, inc_add_11_18_n_30, inc_add_11_18_n_31,
       inc_add_11_18_n_33, inc_add_11_18_n_34;
  wire inc_add_11_18_n_35, inc_add_11_18_n_36, inc_add_11_18_n_40,
       inc_add_11_18_n_41, inc_add_11_18_n_42, inc_add_11_18_n_43,
       inc_add_11_18_n_44, inc_add_11_18_n_45;
  wire inc_add_11_18_n_46, inc_add_11_18_n_51, inc_add_11_18_n_52,
       inc_add_11_18_n_53, inc_add_11_18_n_54, inc_add_11_18_n_56,
       inc_add_11_18_n_60, inc_add_11_18_n_62;
  wire inc_add_11_18_n_63, inc_add_11_18_n_64, inc_add_11_18_n_65,
       inc_add_11_18_n_70, inc_add_11_18_n_71, inc_add_11_18_n_72,
       inc_add_11_18_n_74, inc_add_11_18_n_78;
  wire inc_add_11_18_n_80, inc_add_11_18_n_81, inc_add_11_18_n_84, n_0,
       n_1, n_3, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79;
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_49), .SI (n_18),
       .SE (m), .Q (count[1]));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_50), .SI (n_19),
       .SE (m), .Q (count[2]));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_51), .SI (n_20),
       .SE (n_1), .Q (count[3]));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_52), .SI (n_21),
       .SE (n_1), .Q (count[4]));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_53), .SI (n_22),
       .SE (n_1), .Q (count[5]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_54), .SI (n_23),
       .SE (n_1), .Q (count[6]));
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_55), .SI (n_24),
       .SE (m), .Q (count[7]));
  SDFFRHQX1 \count_reg[8] (.RN (rst), .CK (clk), .D (n_56), .SI (n_25),
       .SE (m), .Q (count[8]));
  SDFFRHQX1 \count_reg[9] (.RN (rst), .CK (clk), .D (n_57), .SI (n_26),
       .SE (m), .Q (count[9]));
  SDFFRHQX1 \count_reg[10] (.RN (rst), .CK (clk), .D (n_58), .SI
       (n_27), .SE (n_1), .Q (count[10]));
  SDFFRHQX1 \count_reg[11] (.RN (rst), .CK (clk), .D (n_59), .SI
       (n_28), .SE (n_1), .Q (count[11]));
  SDFFRHQX1 \count_reg[12] (.RN (rst), .CK (clk), .D (n_60), .SI
       (n_29), .SE (m), .Q (count[12]));
  SDFFRHQX1 \count_reg[13] (.RN (rst), .CK (clk), .D (n_61), .SI
       (n_30), .SE (m), .Q (count[13]));
  SDFFRHQX1 \count_reg[14] (.RN (rst), .CK (clk), .D (n_62), .SI
       (n_31), .SE (m), .Q (count[14]));
  SDFFRHQX1 \count_reg[15] (.RN (rst), .CK (clk), .D (n_63), .SI
       (n_32), .SE (n_1), .Q (count[15]));
  SDFFRHQX1 \count_reg[16] (.RN (rst), .CK (clk), .D (n_64), .SI
       (n_33), .SE (m), .Q (count[16]));
  SDFFRHQX1 \count_reg[17] (.RN (rst), .CK (clk), .D (n_65), .SI
       (n_34), .SE (m), .Q (count[17]));
  SDFFRHQX1 \count_reg[18] (.RN (rst), .CK (clk), .D (n_66), .SI
       (n_35), .SE (m), .Q (count[18]));
  SDFFRHQX1 \count_reg[19] (.RN (rst), .CK (clk), .D (n_67), .SI
       (n_36), .SE (m), .Q (count[19]));
  SDFFRHQX1 \count_reg[20] (.RN (rst), .CK (clk), .D (n_68), .SI
       (n_37), .SE (n_1), .Q (count[20]));
  SDFFRHQX1 \count_reg[21] (.RN (rst), .CK (clk), .D (n_69), .SI
       (n_38), .SE (n_1), .Q (count[21]));
  SDFFRHQX1 \count_reg[22] (.RN (rst), .CK (clk), .D (n_70), .SI
       (n_39), .SE (n_1), .Q (count[22]));
  SDFFRHQX1 \count_reg[23] (.RN (rst), .CK (clk), .D (n_71), .SI
       (n_40), .SE (m), .Q (count[23]));
  SDFFRHQX1 \count_reg[24] (.RN (rst), .CK (clk), .D (n_72), .SI
       (n_41), .SE (m), .Q (count[24]));
  SDFFRHQX1 \count_reg[25] (.RN (rst), .CK (clk), .D (n_73), .SI
       (n_42), .SE (n_1), .Q (count[25]));
  SDFFRHQX1 \count_reg[26] (.RN (rst), .CK (clk), .D (n_74), .SI
       (n_43), .SE (n_1), .Q (count[26]));
  SDFFRHQX1 \count_reg[27] (.RN (rst), .CK (clk), .D (n_75), .SI
       (n_44), .SE (n_1), .Q (count[27]));
  SDFFRHQX1 \count_reg[28] (.RN (rst), .CK (clk), .D (n_76), .SI
       (n_45), .SE (m), .Q (count[28]));
  SDFFRHQX1 \count_reg[29] (.RN (rst), .CK (clk), .D (n_77), .SI
       (n_46), .SE (n_1), .Q (count[29]));
  SDFFRHQX1 \count_reg[30] (.RN (rst), .CK (clk), .D (n_78), .SI
       (n_47), .SE (m), .Q (count[30]));
  SDFFRHQX1 \count_reg[31] (.RN (rst), .CK (clk), .D (n_79), .SI
       (n_48), .SE (n_1), .Q (count[31]));
  CLKINVX1 drc_bufs844(.A (n_0), .Y (n_1));
  CLKINVX1 drc_bufs845(.A (m), .Y (n_0));
  OAI2BB1XL dec_sub_13_18_g1837__2398(.A0N (count[11]), .A1N
       (dec_sub_13_18_n_63), .B0 (dec_sub_13_18_n_19), .Y (n_59));
  NAND2XL dec_sub_13_18_g1838__5107(.A (dec_sub_13_18_n_71), .B
       (dec_sub_13_18_n_35), .Y (n_71));
  OAI2BB1XL dec_sub_13_18_g1839__6260(.A0N (count[7]), .A1N
       (dec_sub_13_18_n_57), .B0 (dec_sub_13_18_n_16), .Y (n_55));
  OAI21X1 dec_sub_13_18_g1840__4319(.A0 (count[22]), .A1
       (dec_sub_13_18_n_45), .B0 (count[23]), .Y (dec_sub_13_18_n_71));
  OAI2BB1X1 dec_sub_13_18_g1841__8428(.A0N (count[25]), .A1N
       (dec_sub_13_18_n_46), .B0 (dec_sub_13_18_n_33), .Y (n_73));
  OAI2BB1XL dec_sub_13_18_g1842__5526(.A0N (count[21]), .A1N
       (dec_sub_13_18_n_44), .B0 (dec_sub_13_18_n_45), .Y (n_69));
  OAI2BB1XL dec_sub_13_18_g1843__6783(.A0N (count[27]), .A1N
       (dec_sub_13_18_n_49), .B0 (dec_sub_13_18_n_32), .Y (n_75));
  OAI2BB1X1 dec_sub_13_18_g1844__3680(.A0N (count[29]), .A1N
       (dec_sub_13_18_n_48), .B0 (dec_sub_13_18_n_47), .Y (n_77));
  OAI2BB1XL dec_sub_13_18_g1845__1617(.A0N (count[19]), .A1N
       (dec_sub_13_18_n_43), .B0 (dec_sub_13_18_n_34), .Y (n_67));
  OAI2BB1X1 dec_sub_13_18_g1846__2802(.A0N (count[10]), .A1N
       (dec_sub_13_18_n_36), .B0 (dec_sub_13_18_n_63), .Y (n_58));
  OAI2BB1XL dec_sub_13_18_g1847__1705(.A0N (count[17]), .A1N
       (dec_sub_13_18_n_37), .B0 (dec_sub_13_18_n_38), .Y (n_65));
  OAI2BB1X1 dec_sub_13_18_g1848__5122(.A0N (count[6]), .A1N
       (dec_sub_13_18_n_29), .B0 (dec_sub_13_18_n_57), .Y (n_54));
  OAI2BB1X1 dec_sub_13_18_g1849__8246(.A0N (count[30]), .A1N
       (dec_sub_13_18_n_47), .B0 (dec_sub_13_18_n_42), .Y (n_78));
  OR2X1 dec_sub_13_18_g1850__7098(.A (count[10]), .B
       (dec_sub_13_18_n_36), .Y (dec_sub_13_18_n_63));
  OAI2BB1X1 dec_sub_13_18_g1851__6131(.A0N (count[15]), .A1N
       (dec_sub_13_18_n_28), .B0 (dec_sub_13_18_n_25), .Y (n_63));
  OAI21X1 dec_sub_13_18_g1852__1881(.A0 (count[22]), .A1
       (dec_sub_13_18_n_45), .B0 (dec_sub_13_18_n_56), .Y (n_70));
  MXI2XL dec_sub_13_18_g1853__5115(.A (dec_sub_13_18_n_42), .B
       (dec_sub_13_18_n_41), .S0 (count[31]), .Y (n_79));
  OR2X1 dec_sub_13_18_g1854__7482(.A (count[6]), .B
       (dec_sub_13_18_n_29), .Y (dec_sub_13_18_n_57));
  NAND2XL dec_sub_13_18_g1855__4733(.A (dec_sub_13_18_n_45), .B
       (count[22]), .Y (dec_sub_13_18_n_56));
  OAI2BB1X1 dec_sub_13_18_g1856__6161(.A0N (count[28]), .A1N
       (dec_sub_13_18_n_32), .B0 (dec_sub_13_18_n_48), .Y (n_76));
  OAI2BB1X1 dec_sub_13_18_g1857__9315(.A0N (count[26]), .A1N
       (dec_sub_13_18_n_33), .B0 (dec_sub_13_18_n_49), .Y (n_74));
  OAI2BB1X1 dec_sub_13_18_g1858__9945(.A0N (count[24]), .A1N
       (dec_sub_13_18_n_35), .B0 (dec_sub_13_18_n_46), .Y (n_72));
  OAI2BB1X1 dec_sub_13_18_g1859__2883(.A0N (count[20]), .A1N
       (dec_sub_13_18_n_34), .B0 (dec_sub_13_18_n_44), .Y (n_68));
  OAI2BB1X1 dec_sub_13_18_g1860__2346(.A0N (count[18]), .A1N
       (dec_sub_13_18_n_38), .B0 (dec_sub_13_18_n_43), .Y (n_66));
  AO21X1 dec_sub_13_18_g1861__1666(.A0 (count[13]), .A1
       (dec_sub_13_18_n_23), .B0 (dec_sub_13_18_n_21), .Y (n_61));
  OR2X1 dec_sub_13_18_g1862__7410(.A (count[26]), .B
       (dec_sub_13_18_n_33), .Y (dec_sub_13_18_n_49));
  OR2X1 dec_sub_13_18_g1863__6417(.A (count[28]), .B
       (dec_sub_13_18_n_32), .Y (dec_sub_13_18_n_48));
  NAND2BX1 dec_sub_13_18_g1864__5477(.AN (dec_sub_13_18_n_32), .B
       (dec_sub_13_18_n_1), .Y (dec_sub_13_18_n_47));
  OR2X1 dec_sub_13_18_g1865__2398(.A (count[24]), .B
       (dec_sub_13_18_n_35), .Y (dec_sub_13_18_n_46));
  NAND2BX1 dec_sub_13_18_g1866__5107(.AN (dec_sub_13_18_n_34), .B
       (dec_sub_13_18_n_5), .Y (dec_sub_13_18_n_45));
  INVX1 dec_sub_13_18_g1867(.A (dec_sub_13_18_n_41), .Y
       (dec_sub_13_18_n_42));
  OAI2BB1X1 dec_sub_13_18_g1868__6260(.A0N (count[16]), .A1N
       (dec_sub_13_18_n_25), .B0 (dec_sub_13_18_n_37), .Y (n_64));
  OAI2BB1X1 dec_sub_13_18_g1869__4319(.A0N (count[9]), .A1N
       (dec_sub_13_18_n_20), .B0 (dec_sub_13_18_n_36), .Y (n_57));
  OR2X1 dec_sub_13_18_g1870__8428(.A (count[20]), .B
       (dec_sub_13_18_n_34), .Y (dec_sub_13_18_n_44));
  OR2X1 dec_sub_13_18_g1871__5526(.A (count[18]), .B
       (dec_sub_13_18_n_38), .Y (dec_sub_13_18_n_43));
  NOR4BX1 dec_sub_13_18_g1872__6783(.AN (dec_sub_13_18_n_1), .B
       (count[30]), .C (dec_sub_13_18_n_10), .D (dec_sub_13_18_n_35),
       .Y (dec_sub_13_18_n_41));
  NAND2XL dec_sub_13_18_g1873__3680(.A (dec_sub_13_18_n_26), .B
       (dec_sub_13_18_n_2), .Y (dec_sub_13_18_n_38));
  NAND2BX1 dec_sub_13_18_g1874__1617(.AN (count[16]), .B
       (dec_sub_13_18_n_26), .Y (dec_sub_13_18_n_37));
  OR2X1 dec_sub_13_18_g1875__2802(.A (count[9]), .B
       (dec_sub_13_18_n_20), .Y (dec_sub_13_18_n_36));
  NAND2XL dec_sub_13_18_g1876__1705(.A (dec_sub_13_18_n_26), .B
       (dec_sub_13_18_n_12), .Y (dec_sub_13_18_n_35));
  NAND2XL dec_sub_13_18_g1877__5122(.A (dec_sub_13_18_n_26), .B
       (dec_sub_13_18_n_9), .Y (dec_sub_13_18_n_34));
  NAND3X1 dec_sub_13_18_g1878__8246(.A (dec_sub_13_18_n_3), .B
       (dec_sub_13_18_n_12), .C (dec_sub_13_18_n_26), .Y
       (dec_sub_13_18_n_33));
  NAND3BX1 dec_sub_13_18_g1879__7098(.AN (dec_sub_13_18_n_10), .B
       (dec_sub_13_18_n_12), .C (dec_sub_13_18_n_26), .Y
       (dec_sub_13_18_n_32));
  OAI2BB1X1 dec_sub_13_18_g1880__6131(.A0N (count[5]), .A1N
       (dec_sub_13_18_n_17), .B0 (dec_sub_13_18_n_29), .Y (n_53));
  OAI21X1 dec_sub_13_18_g1881__1881(.A0 (dec_sub_13_18_n_0), .A1
       (dec_sub_13_18_n_21), .B0 (dec_sub_13_18_n_28), .Y (n_62));
  OR2X1 dec_sub_13_18_g1882__5115(.A (count[5]), .B
       (dec_sub_13_18_n_17), .Y (dec_sub_13_18_n_29));
  NAND2XL dec_sub_13_18_g1883__7482(.A (dec_sub_13_18_n_21), .B
       (dec_sub_13_18_n_0), .Y (dec_sub_13_18_n_28));
  OAI2BB1X1 dec_sub_13_18_g1884__4733(.A0N (count[12]), .A1N
       (dec_sub_13_18_n_19), .B0 (dec_sub_13_18_n_23), .Y (n_60));
  INVX1 dec_sub_13_18_g1885(.A (dec_sub_13_18_n_26), .Y
       (dec_sub_13_18_n_25));
  NOR3BX1 dec_sub_13_18_g1886__6161(.AN (dec_sub_13_18_n_21), .B
       (count[15]), .C (count[14]), .Y (dec_sub_13_18_n_26));
  OAI2BB1XL dec_sub_13_18_g1887__9315(.A0N (count[3]), .A1N
       (dec_sub_13_18_n_14), .B0 (dec_sub_13_18_n_13), .Y (n_51));
  OR2XL dec_sub_13_18_g1888__9945(.A (count[12]), .B
       (dec_sub_13_18_n_19), .Y (dec_sub_13_18_n_23));
  OAI2BB1X1 dec_sub_13_18_g1889__2883(.A0N (count[8]), .A1N
       (dec_sub_13_18_n_16), .B0 (dec_sub_13_18_n_20), .Y (n_56));
  NOR3X1 dec_sub_13_18_g1890__2346(.A (count[13]), .B (count[12]), .C
       (dec_sub_13_18_n_19), .Y (dec_sub_13_18_n_21));
  OR2X1 dec_sub_13_18_g1891__1666(.A (count[8]), .B
       (dec_sub_13_18_n_16), .Y (dec_sub_13_18_n_20));
  NAND2BX1 dec_sub_13_18_g1892__7410(.AN (dec_sub_13_18_n_16), .B
       (dec_sub_13_18_n_8), .Y (dec_sub_13_18_n_19));
  OAI2BB1X1 dec_sub_13_18_g1893__6417(.A0N (count[4]), .A1N
       (dec_sub_13_18_n_13), .B0 (dec_sub_13_18_n_17), .Y (n_52));
  OR2X1 dec_sub_13_18_g1894__5477(.A (count[4]), .B
       (dec_sub_13_18_n_13), .Y (dec_sub_13_18_n_17));
  NAND2BX1 dec_sub_13_18_g1895__2398(.AN (dec_sub_13_18_n_13), .B
       (dec_sub_13_18_n_7), .Y (dec_sub_13_18_n_16));
  OAI2BB1X1 dec_sub_13_18_g1896__5107(.A0N (count[2]), .A1N
       (dec_sub_13_18_n_6), .B0 (dec_sub_13_18_n_14), .Y (n_50));
  OR2X1 dec_sub_13_18_g1897__6260(.A (count[2]), .B
       (dec_sub_13_18_n_6), .Y (dec_sub_13_18_n_14));
  OR3X1 dec_sub_13_18_g1898__4319(.A (count[3]), .B (count[2]), .C
       (dec_sub_13_18_n_6), .Y (dec_sub_13_18_n_13));
  NOR4BBX1 dec_sub_13_18_g1899__8428(.AN (dec_sub_13_18_n_5), .BN
       (dec_sub_13_18_n_9), .C (count[23]), .D (count[22]), .Y
       (dec_sub_13_18_n_12));
  OAI2BB1X1 dec_sub_13_18_g1900__5526(.A0N (count[1]), .A1N (count[0]),
       .B0 (dec_sub_13_18_n_6), .Y (n_49));
  NAND2XL dec_sub_13_18_g1901__6783(.A (dec_sub_13_18_n_3), .B
       (dec_sub_13_18_n_4), .Y (dec_sub_13_18_n_10));
  NOR3BX1 dec_sub_13_18_g1902__3680(.AN (dec_sub_13_18_n_2), .B
       (count[19]), .C (count[18]), .Y (dec_sub_13_18_n_9));
  NOR4X1 dec_sub_13_18_g1903__1617(.A (count[11]), .B (count[9]), .C
       (count[10]), .D (count[8]), .Y (dec_sub_13_18_n_8));
  NOR4X1 dec_sub_13_18_g1904__2802(.A (count[7]), .B (count[5]), .C
       (count[6]), .D (count[4]), .Y (dec_sub_13_18_n_7));
  OR2X1 dec_sub_13_18_g1905__1705(.A (count[1]), .B (count[0]), .Y
       (dec_sub_13_18_n_6));
  NOR2XL dec_sub_13_18_g1906__5122(.A (count[21]), .B (count[20]), .Y
       (dec_sub_13_18_n_5));
  NOR2XL dec_sub_13_18_g1907__8246(.A (count[27]), .B (count[26]), .Y
       (dec_sub_13_18_n_4));
  NOR2XL dec_sub_13_18_g1908__7098(.A (count[25]), .B (count[24]), .Y
       (dec_sub_13_18_n_3));
  NOR2XL dec_sub_13_18_g1909__6131(.A (count[17]), .B (count[16]), .Y
       (dec_sub_13_18_n_2));
  NOR2XL dec_sub_13_18_g1910__1881(.A (count[29]), .B (count[28]), .Y
       (dec_sub_13_18_n_1));
  INVX1 dec_sub_13_18_g1911(.A (count[14]), .Y (dec_sub_13_18_n_0));
  OAI21X1 inc_add_11_18_g477__5115(.A0 (count[19]), .A1
       (inc_add_11_18_n_78), .B0 (inc_add_11_18_n_84), .Y (n_36));
  NAND2XL inc_add_11_18_g478__7482(.A (inc_add_11_18_n_78), .B
       (count[19]), .Y (inc_add_11_18_n_84));
  OAI21X1 inc_add_11_18_g479__4733(.A0 (count[11]), .A1
       (inc_add_11_18_n_64), .B0 (inc_add_11_18_n_80), .Y (n_28));
  OAI21X1 inc_add_11_18_g480__6161(.A0 (count[31]), .A1
       (inc_add_11_18_n_65), .B0 (inc_add_11_18_n_81), .Y (n_48));
  NAND2XL inc_add_11_18_g481__9315(.A (inc_add_11_18_n_65), .B
       (count[31]), .Y (inc_add_11_18_n_81));
  NAND2XL inc_add_11_18_g482__9945(.A (inc_add_11_18_n_64), .B
       (count[11]), .Y (inc_add_11_18_n_80));
  OA21XL inc_add_11_18_g483__2883(.A0 (count[18]), .A1
       (inc_add_11_18_n_74), .B0 (inc_add_11_18_n_78), .Y (n_35));
  NAND2XL inc_add_11_18_g484__2346(.A (inc_add_11_18_n_74), .B
       (count[18]), .Y (inc_add_11_18_n_78));
  OAI21X1 inc_add_11_18_g485__1666(.A0 (count[29]), .A1
       (inc_add_11_18_n_54), .B0 (inc_add_11_18_n_72), .Y (n_46));
  OAI21X1 inc_add_11_18_g486__7410(.A0 (count[27]), .A1
       (inc_add_11_18_n_53), .B0 (inc_add_11_18_n_71), .Y (n_44));
  OAI21X1 inc_add_11_18_g487__6417(.A0 (count[23]), .A1
       (inc_add_11_18_n_52), .B0 (inc_add_11_18_n_70), .Y (n_40));
  ADDHX1 inc_add_11_18_g488__5477(.A (count[17]), .B
       (inc_add_11_18_n_34), .CO (inc_add_11_18_n_74), .S (n_34));
  NAND2XL inc_add_11_18_g489__2398(.A (inc_add_11_18_n_54), .B
       (count[29]), .Y (inc_add_11_18_n_72));
  NAND2XL inc_add_11_18_g490__5107(.A (inc_add_11_18_n_53), .B
       (count[27]), .Y (inc_add_11_18_n_71));
  NAND2XL inc_add_11_18_g491__6260(.A (inc_add_11_18_n_52), .B
       (count[23]), .Y (inc_add_11_18_n_70));
  OA21XL inc_add_11_18_g492__4319(.A0 (count[10]), .A1
       (inc_add_11_18_n_43), .B0 (inc_add_11_18_n_64), .Y (n_27));
  OA21XL inc_add_11_18_g493__8428(.A0 (count[30]), .A1
       (inc_add_11_18_n_56), .B0 (inc_add_11_18_n_65), .Y (n_47));
  OAI21X1 inc_add_11_18_g494__5526(.A0 (count[25]), .A1
       (inc_add_11_18_n_44), .B0 (inc_add_11_18_n_63), .Y (n_42));
  OAI21X1 inc_add_11_18_g495__6783(.A0 (count[21]), .A1
       (inc_add_11_18_n_40), .B0 (inc_add_11_18_n_62), .Y (n_38));
  NAND2XL inc_add_11_18_g496__3680(.A (inc_add_11_18_n_56), .B
       (count[30]), .Y (inc_add_11_18_n_65));
  NAND2XL inc_add_11_18_g497__1617(.A (inc_add_11_18_n_43), .B
       (count[10]), .Y (inc_add_11_18_n_64));
  NAND2XL inc_add_11_18_g498__2802(.A (inc_add_11_18_n_44), .B
       (count[25]), .Y (inc_add_11_18_n_63));
  NAND2XL inc_add_11_18_g499__1705(.A (inc_add_11_18_n_40), .B
       (count[21]), .Y (inc_add_11_18_n_62));
  OAI21X1 inc_add_11_18_g500__5122(.A0 (count[15]), .A1
       (inc_add_11_18_n_33), .B0 (inc_add_11_18_n_60), .Y (n_32));
  NAND2XL inc_add_11_18_g501__8246(.A (inc_add_11_18_n_33), .B
       (count[15]), .Y (inc_add_11_18_n_60));
  OA21XL inc_add_11_18_g502__7098(.A0 (count[28]), .A1
       (inc_add_11_18_n_41), .B0 (inc_add_11_18_n_54), .Y (n_45));
  OA21XL inc_add_11_18_g503__6131(.A0 (count[26]), .A1
       (inc_add_11_18_n_46), .B0 (inc_add_11_18_n_53), .Y (n_43));
  OA21XL inc_add_11_18_g504__1881(.A0 (count[22]), .A1
       (inc_add_11_18_n_45), .B0 (inc_add_11_18_n_52), .Y (n_39));
  AND3X1 inc_add_11_18_g505__5115(.A (count[29]), .B (count[28]), .C
       (inc_add_11_18_n_41), .Y (inc_add_11_18_n_56));
  OAI21X1 inc_add_11_18_g506__7482(.A0 (count[13]), .A1
       (inc_add_11_18_n_26), .B0 (inc_add_11_18_n_51), .Y (n_30));
  NAND2XL inc_add_11_18_g507__4733(.A (inc_add_11_18_n_41), .B
       (count[28]), .Y (inc_add_11_18_n_54));
  NAND2XL inc_add_11_18_g508__6161(.A (inc_add_11_18_n_46), .B
       (count[26]), .Y (inc_add_11_18_n_53));
  NAND2XL inc_add_11_18_g509__9315(.A (inc_add_11_18_n_45), .B
       (count[22]), .Y (inc_add_11_18_n_52));
  NAND2XL inc_add_11_18_g510__9945(.A (inc_add_11_18_n_26), .B
       (count[13]), .Y (inc_add_11_18_n_51));
  OA21XL inc_add_11_18_g511__2883(.A0 (count[20]), .A1
       (inc_add_11_18_n_35), .B0 (inc_add_11_18_n_40), .Y (n_37));
  AOI21X1 inc_add_11_18_g512__2346(.A0 (inc_add_11_18_n_1), .A1
       (inc_add_11_18_n_22), .B0 (inc_add_11_18_n_43), .Y (n_26));
  OA21XL inc_add_11_18_g513__1666(.A0 (count[24]), .A1
       (inc_add_11_18_n_30), .B0 (inc_add_11_18_n_44), .Y (n_41));
  OAI21X1 inc_add_11_18_g514__7410(.A0 (count[7]), .A1
       (inc_add_11_18_n_21), .B0 (inc_add_11_18_n_42), .Y (n_24));
  NAND2XL inc_add_11_18_g515__6417(.A (inc_add_11_18_n_21), .B
       (count[7]), .Y (inc_add_11_18_n_42));
  NOR2XL inc_add_11_18_g516__5477(.A (inc_add_11_18_n_6), .B
       (inc_add_11_18_n_31), .Y (inc_add_11_18_n_46));
  NOR2BX1 inc_add_11_18_g517__2398(.AN (inc_add_11_18_n_35), .B
       (inc_add_11_18_n_3), .Y (inc_add_11_18_n_45));
  NAND2XL inc_add_11_18_g518__5107(.A (inc_add_11_18_n_30), .B
       (count[24]), .Y (inc_add_11_18_n_44));
  NOR2XL inc_add_11_18_g519__6260(.A (inc_add_11_18_n_1), .B
       (inc_add_11_18_n_22), .Y (inc_add_11_18_n_43));
  OA21XL inc_add_11_18_g520__4319(.A0 (count[14]), .A1
       (inc_add_11_18_n_27), .B0 (inc_add_11_18_n_33), .Y (n_31));
  AOI21XL inc_add_11_18_g521__8428(.A0 (inc_add_11_18_n_0), .A1
       (inc_add_11_18_n_23), .B0 (inc_add_11_18_n_34), .Y (n_33));
  OAI21X1 inc_add_11_18_g522__5526(.A0 (count[5]), .A1
       (inc_add_11_18_n_17), .B0 (inc_add_11_18_n_36), .Y (n_22));
  NOR4BBX1 inc_add_11_18_g523__6783(.AN (count[27]), .BN (count[26]),
       .C (inc_add_11_18_n_6), .D (inc_add_11_18_n_31), .Y
       (inc_add_11_18_n_41));
  NAND2XL inc_add_11_18_g524__3680(.A (inc_add_11_18_n_35), .B
       (count[20]), .Y (inc_add_11_18_n_40));
  NAND2XL inc_add_11_18_g525__1617(.A (inc_add_11_18_n_17), .B
       (count[5]), .Y (inc_add_11_18_n_36));
  NOR2XL inc_add_11_18_g526__2802(.A (inc_add_11_18_n_9), .B
       (inc_add_11_18_n_23), .Y (inc_add_11_18_n_35));
  NOR2XL inc_add_11_18_g527__1705(.A (inc_add_11_18_n_0), .B
       (inc_add_11_18_n_23), .Y (inc_add_11_18_n_34));
  NAND2XL inc_add_11_18_g528__5122(.A (inc_add_11_18_n_27), .B
       (count[14]), .Y (inc_add_11_18_n_33));
  OA21X1 inc_add_11_18_g529__8246(.A0 (count[12]), .A1
       (inc_add_11_18_n_20), .B0 (inc_add_11_18_n_26), .Y (n_29));
  INVX1 inc_add_11_18_g530(.A (inc_add_11_18_n_31), .Y
       (inc_add_11_18_n_30));
  NAND4BXL inc_add_11_18_g531__7098(.AN (inc_add_11_18_n_23), .B
       (count[23]), .C (inc_add_11_18_n_13), .D (count[22]), .Y
       (inc_add_11_18_n_31));
  OAI21X1 inc_add_11_18_g532__6131(.A0 (count[3]), .A1
       (inc_add_11_18_n_14), .B0 (inc_add_11_18_n_28), .Y (n_20));
  NAND2XL inc_add_11_18_g533__1881(.A (inc_add_11_18_n_14), .B
       (count[3]), .Y (inc_add_11_18_n_28));
  NOR2BX1 inc_add_11_18_g534__5115(.AN (inc_add_11_18_n_20), .B
       (inc_add_11_18_n_2), .Y (inc_add_11_18_n_27));
  NAND2XL inc_add_11_18_g535__7482(.A (inc_add_11_18_n_20), .B
       (count[12]), .Y (inc_add_11_18_n_26));
  OA21X1 inc_add_11_18_g536__4733(.A0 (count[6]), .A1
       (inc_add_11_18_n_18), .B0 (inc_add_11_18_n_21), .Y (n_23));
  OA21XL inc_add_11_18_g537__6161(.A0 (count[8]), .A1
       (inc_add_11_18_n_16), .B0 (inc_add_11_18_n_22), .Y (n_25));
  NAND4XL inc_add_11_18_g538__9315(.A (inc_add_11_18_n_16), .B
       (count[15]), .C (count[14]), .D (inc_add_11_18_n_12), .Y
       (inc_add_11_18_n_23));
  NAND2XL inc_add_11_18_g539__9945(.A (inc_add_11_18_n_16), .B
       (count[8]), .Y (inc_add_11_18_n_22));
  NAND2XL inc_add_11_18_g540__2883(.A (inc_add_11_18_n_18), .B
       (count[6]), .Y (inc_add_11_18_n_21));
  NOR2BX1 inc_add_11_18_g541__2346(.AN (inc_add_11_18_n_16), .B
       (inc_add_11_18_n_8), .Y (inc_add_11_18_n_20));
  OA21X1 inc_add_11_18_g542__1666(.A0 (count[4]), .A1
       (inc_add_11_18_n_10), .B0 (inc_add_11_18_n_17), .Y (n_21));
  NOR2XL inc_add_11_18_g543__7410(.A (inc_add_11_18_n_4), .B
       (inc_add_11_18_n_11), .Y (inc_add_11_18_n_18));
  NAND2XL inc_add_11_18_g544__6417(.A (inc_add_11_18_n_10), .B
       (count[4]), .Y (inc_add_11_18_n_17));
  NOR4BBX1 inc_add_11_18_g545__5477(.AN (count[7]), .BN (count[6]), .C
       (inc_add_11_18_n_4), .D (inc_add_11_18_n_11), .Y
       (inc_add_11_18_n_16));
  OA21X1 inc_add_11_18_g546__2398(.A0 (count[2]), .A1
       (inc_add_11_18_n_5), .B0 (inc_add_11_18_n_14), .Y (n_19));
  NAND2XL inc_add_11_18_g547__5107(.A (inc_add_11_18_n_5), .B
       (count[2]), .Y (inc_add_11_18_n_14));
  NOR2XL inc_add_11_18_g548__6260(.A (inc_add_11_18_n_3), .B
       (inc_add_11_18_n_9), .Y (inc_add_11_18_n_13));
  NOR2XL inc_add_11_18_g549__4319(.A (inc_add_11_18_n_2), .B
       (inc_add_11_18_n_8), .Y (inc_add_11_18_n_12));
  INVX1 inc_add_11_18_g550(.A (inc_add_11_18_n_11), .Y
       (inc_add_11_18_n_10));
  NAND3X1 inc_add_11_18_g551__8428(.A (count[2]), .B (count[3]), .C
       (inc_add_11_18_n_5), .Y (inc_add_11_18_n_11));
  NAND4XL inc_add_11_18_g552__5526(.A (count[18]), .B (count[19]), .C
       (count[17]), .D (count[16]), .Y (inc_add_11_18_n_9));
  NAND4XL inc_add_11_18_g553__6783(.A (count[10]), .B (count[11]), .C
       (count[9]), .D (count[8]), .Y (inc_add_11_18_n_8));
  AOI2BB1X1 inc_add_11_18_g554__3680(.A0N (count[1]), .A1N (count[0]),
       .B0 (inc_add_11_18_n_5), .Y (n_18));
  NAND2XL inc_add_11_18_g555__1617(.A (count[24]), .B (count[25]), .Y
       (inc_add_11_18_n_6));
  AND2X1 inc_add_11_18_g556__2802(.A (count[1]), .B (count[0]), .Y
       (inc_add_11_18_n_5));
  NAND2XL inc_add_11_18_g557__1705(.A (count[4]), .B (count[5]), .Y
       (inc_add_11_18_n_4));
  NAND2XL inc_add_11_18_g558__5122(.A (count[20]), .B (count[21]), .Y
       (inc_add_11_18_n_3));
  NAND2XL inc_add_11_18_g559__8246(.A (count[12]), .B (count[13]), .Y
       (inc_add_11_18_n_2));
  INVX1 inc_add_11_18_g560(.A (count[9]), .Y (inc_add_11_18_n_1));
  INVX1 inc_add_11_18_g561(.A (count[16]), .Y (inc_add_11_18_n_0));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_3), .Q (count[0]),
       .QN (n_3));
endmodule

