
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 22:58:20 IST (Feb 22 2025 17:28:20 UTC)

// Verification Directory fv/mod10

module mod10(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  DFFRHQX2 \count_reg[3] (.RN (n_9), .CK (clk), .D (n_10), .Q
       (count[3]));
  NOR2XL g129__2398(.A (n_6), .B (n_8), .Y (n_10));
  DFFRHQX2 \count_reg[1] (.RN (n_9), .CK (clk), .D (n_7), .Q
       (count[1]));
  AOI21XL g130__5107(.A0 (count[3]), .A1 (n_4), .B0 (n_5), .Y (n_8));
  DFFRHQX2 \count_reg[2] (.RN (n_9), .CK (clk), .D (n_3), .Q
       (count[2]));
  NOR3X1 g136__6260(.A (n_0), .B (n_2), .C (n_6), .Y (n_7));
  NOR2XL g132__4319(.A (count[3]), .B (n_4), .Y (n_5));
  OA21XL g134__8428(.A0 (count[2]), .A1 (n_2), .B0 (n_4), .Y (n_3));
  NOR4BX1 g137__5526(.AN (count[3]), .B (count[1]), .C (count[2]), .D
       (n_1), .Y (n_6));
  NAND2XL g135__6783(.A (count[2]), .B (n_2), .Y (n_4));
  NOR2XL g139__3680(.A (count[0]), .B (count[1]), .Y (n_0));
  AND2X1 g140__1617(.A (count[1]), .B (count[0]), .Y (n_2));
  INVXL g141(.A (reset), .Y (n_9));
  DFFRX2 \count_reg[0] (.RN (n_9), .CK (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
endmodule

